name: "🐛 Bug report"
description: Report a bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: os_details
    attributes:
      label: System details
      placeholder: "e.g. Windows 11 / Ubuntu 24.04"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App version
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Go to "Settings" > "Advanced" > "Open logs folder" > then copy the entire contents of `app.log`.
      render: shell
    validations:
      required: false

  - type: upload
    id: attachments
    attributes:
      label: Screenshots or video
      description: If applicable, attach screenshots, video, or other files.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Final checks
      options:
        - label: I've searched for similar issues
          required: true
        - label: I'm using the latest version
          required: true
