blank_issues_enabled: false
contact_links:
  - name: Create another issue
    url: https://github.com/deeffest/Youtube-Music-Desktop-Player/issues/new
    about: Unless it's a bug report or an enhancement or feature request
