name: "🚀 Feature request"
description: Suggest an idea
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What is the current limitation?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any screenshots or examples.
