# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Program Files\Projects\Youtube-Music-Desktop-Player-main\core\ui\mini_player_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(360, 150))
        Dialog.setMaximumSize(QtCore.QSize(360, 150))
        Dialog.setMouseTracking(True)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: rgb(39,39,39);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 18, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(16, -1, 16, 6)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.StrongBodyLabel = StrongBodyLabel(Dialog)
        self.StrongBodyLabel.setText("")
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout_2.addWidget(self.StrongBodyLabel)
        self.BodyLabel_2 = BodyLabel(Dialog)
        self.BodyLabel_2.setStyleSheet("QLabel {\n"
"    color: lightgray;\n"
"    font-size: 13px;\n"
"}")
        self.BodyLabel_2.setText("")
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout_2.addWidget(self.BodyLabel_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(4, 3, 4, 18)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.TransparentToolButton = TransparentToolButton(Dialog)
        self.TransparentToolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.TransparentToolButton.setMaximumSize(QtCore.QSize(40, 40))
        self.TransparentToolButton.setIconSize(QtCore.QSize(20, 20))
        self.TransparentToolButton.setObjectName("TransparentToolButton")
        self.horizontalLayout_3.addWidget(self.TransparentToolButton)
        self.TransparentToolButton_2 = TransparentToolButton(Dialog)
        self.TransparentToolButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.TransparentToolButton_2.setMaximumSize(QtCore.QSize(40, 40))
        self.TransparentToolButton_2.setIconSize(QtCore.QSize(20, 20))
        self.TransparentToolButton_2.setObjectName("TransparentToolButton_2")
        self.horizontalLayout_3.addWidget(self.TransparentToolButton_2)
        self.TransparentToolButton_3 = TransparentToolButton(Dialog)
        self.TransparentToolButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.TransparentToolButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.TransparentToolButton_3.setIconSize(QtCore.QSize(20, 20))
        self.TransparentToolButton_3.setObjectName("TransparentToolButton_3")
        self.horizontalLayout_3.addWidget(self.TransparentToolButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.TransparentToolButton.setShortcut(_translate("Dialog", "Left"))
        self.TransparentToolButton_2.setShortcut(_translate("Dialog", "Space"))
        self.TransparentToolButton_3.setShortcut(_translate("Dialog", "Right"))
from qfluentwidgets import BodyLabel, StrongBodyLabel, TransparentToolButton
