# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/ui/about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(383, 313)
        AboutDialog.setMinimumSize(QtCore.QSize(383, 313))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(AboutDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(6, 9, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(72, 72))
        self.label.setMaximumSize(QtCore.QSize(72, 72))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, 6, 9, 14)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SubtitleLabel = SubtitleLabel(self.frame)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout_3.addWidget(self.SubtitleLabel)
        self.BodyLabel_2 = BodyLabel(self.frame)
        self.BodyLabel_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.BodyLabel_2.setText("")
        self.BodyLabel_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout_3.addWidget(self.BodyLabel_2)
        self.BodyLabel = BodyLabel(self.frame)
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_3.addWidget(self.BodyLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = BodyLabel(self.frame)
        self.label_3.setStyleSheet("BodyLabel {\n"
"    color: #A0A0A0;\n"
"    font-family: Consolas, monospace;\n"
"    font-size: 12px;\n"
"    padding: 1px 4px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = BodyLabel(self.frame)
        self.label_5.setStyleSheet("BodyLabel {\n"
"    color: #A0A0A0;\n"
"    font-family: Consolas, monospace;\n"
"    font-size: 12px;\n"
"    padding: 1px 4px;\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = BodyLabel(self.frame)
        self.label_7.setStyleSheet("BodyLabel {\n"
"    color: #A0A0A0;\n"
"    font-family: Consolas, monospace;\n"
"    font-size: 12px;\n"
"    padding: 1px 4px;\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.BodyLabel_3 = BodyLabel(self.frame)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.verticalLayout_3.addWidget(self.BodyLabel_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.ButtonBox = QtWidgets.QFrame(AboutDialog)
        self.ButtonBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonBox.setObjectName("ButtonBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ButtonBox)
        self.verticalLayout.setContentsMargins(12, 16, 12, 16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel_4 = BodyLabel(self.ButtonBox)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout_5.addWidget(self.BodyLabel_4)
        self.HyperlinkLabel = HyperlinkLabel(self.ButtonBox)
        self.HyperlinkLabel.setProperty("url", QtCore.QUrl("https://icons8.com"))
        self.HyperlinkLabel.setObjectName("HyperlinkLabel")
        self.horizontalLayout_5.addWidget(self.HyperlinkLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.PushButton = PushButton(self.ButtonBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton.sizePolicy().hasHeightForWidth())
        self.PushButton.setSizePolicy(sizePolicy)
        self.PushButton.setIconSize(QtCore.QSize(18, 18))
        self.PushButton.setProperty("hasIcon", True)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_5.addWidget(self.PushButton)
        self.PrimaryPushButton = PrimaryPushButton(self.ButtonBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrimaryPushButton.sizePolicy().hasHeightForWidth())
        self.PrimaryPushButton.setSizePolicy(sizePolicy)
        self.PrimaryPushButton.setMinimumSize(QtCore.QSize(115, 0))
        self.PrimaryPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout_5.addWidget(self.PrimaryPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.ButtonBox)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "Dialog"))
        self.SubtitleLabel.setText(_translate("AboutDialog", "Youtube Music Desktop Player"))
        self.BodyLabel.setText(_translate("AboutDialog", "<html><head/><body><p><span style=\" color:#d3d3d3;\">Turns the YouTube Music site into a cross-platform desktop application using QtWebEngine.</span></p></body></html>"))
        self.BodyLabel_3.setText(_translate("AboutDialog", "Created with ❤️ by deeffest, 2024-2025"))
        self.BodyLabel_4.setText(_translate("AboutDialog", "Icons by"))
        self.HyperlinkLabel.setText(_translate("AboutDialog", "Icons8"))
        self.PushButton.setText(_translate("AboutDialog", "Visit GitHub"))
        self.PrimaryPushButton.setText(_translate("AboutDialog", "Close"))
from qfluentwidgets import BodyLabel, HyperlinkLabel, PrimaryPushButton, PushButton, SubtitleLabel
