# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/ui/comments_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommentsDialog(object):
    def setupUi(self, CommentsDialog):
        CommentsDialog.setObjectName("CommentsDialog")
        CommentsDialog.resize(450, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CommentsDialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(CommentsDialog)
        QtCore.QMetaObject.connectSlotsByName(CommentsDialog)

    def retranslateUi(self, CommentsDialog):
        _translate = QtCore.QCoreApplication.translate
        CommentsDialog.setWindowTitle(_translate("CommentsDialog", "Comments"))
