# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ToolBar = QtWidgets.QFrame(self.centralwidget)
        self.ToolBar.setObjectName("ToolBar")
        self.toolbar_layout = QtWidgets.QHBoxLayout(self.ToolBar)
        self.toolbar_layout.setContentsMargins(6, 4, 6, 4)
        self.toolbar_layout.setSpacing(0)
        self.toolbar_layout.setObjectName("toolbar_layout")
        self.back_tbutton = TransparentToolButton(self.ToolBar)
        self.back_tbutton.setEnabled(False)
        self.back_tbutton.setObjectName("back_tbutton")
        self.toolbar_layout.addWidget(self.back_tbutton)
        self.forward_tbutton = TransparentToolButton(self.ToolBar)
        self.forward_tbutton.setEnabled(False)
        self.forward_tbutton.setObjectName("forward_tbutton")
        self.toolbar_layout.addWidget(self.forward_tbutton)
        self.home_tbutton = TransparentToolButton(self.ToolBar)
        self.home_tbutton.setObjectName("home_tbutton")
        self.toolbar_layout.addWidget(self.home_tbutton)
        self.reload_tbutton = TransparentToolButton(self.ToolBar)
        self.reload_tbutton.setObjectName("reload_tbutton")
        self.toolbar_layout.addWidget(self.reload_tbutton)
        spacerItem = QtWidgets.QSpacerItem(6, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.toolbar_layout.addItem(spacerItem)
        self.url_label = BodyLabel(self.ToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_label.sizePolicy().hasHeightForWidth())
        self.url_label.setSizePolicy(sizePolicy)
        self.url_label.setMinimumSize(QtCore.QSize(30, 0))
        self.url_label.setStyleSheet("QLabel {\n"
"    color: rgb(210, 210, 210);\n"
"    background-color: rgb(33, 33, 33);\n"
"    border: 1px solid transparent;\n"
"    border-radius: 6px;\n"
"    padding: 3px 6px;\n"
"}\n"
"QLabel:hover {\n"
"    border: 1px solid rgb(255, 41, 41);\n"
"}\n"
"")
        self.url_label.setObjectName("url_label")
        self.toolbar_layout.addWidget(self.url_label)
        spacerItem1 = QtWidgets.QSpacerItem(6, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.toolbar_layout.addItem(spacerItem1)
        self.download_ddtbutton = TransparentDropDownToolButton(self.ToolBar)
        self.download_ddtbutton.setObjectName("download_ddtbutton")
        self.toolbar_layout.addWidget(self.download_ddtbutton)
        self.watch_in_pip_tbutton = TransparentToolButtonWithMenu(self.ToolBar)
        self.watch_in_pip_tbutton.setObjectName("watch_in_pip_tbutton")
        self.toolbar_layout.addWidget(self.watch_in_pip_tbutton)
        self.settings_ddtbutton = TransparentToolButtonWithMenu(self.ToolBar)
        self.settings_ddtbutton.setObjectName("settings_ddtbutton")
        self.toolbar_layout.addWidget(self.settings_ddtbutton)
        self.plugins_ddtbutton = TransparentDropDownToolButton(self.ToolBar)
        self.plugins_ddtbutton.setText("")
        self.plugins_ddtbutton.setObjectName("plugins_ddtbutton")
        self.toolbar_layout.addWidget(self.plugins_ddtbutton)
        self.more_ddtbutton = TransparentToolButtonWithMenu(self.ToolBar)
        self.more_ddtbutton.setObjectName("more_ddtbutton")
        self.toolbar_layout.addWidget(self.more_ddtbutton)
        self.verticalLayout.addWidget(self.ToolBar)
        self.MainLayout = QtWidgets.QHBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        spacerItem2 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.MainLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.MainLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Music Desktop Player"))
        self.back_tbutton.setToolTip(_translate("MainWindow", "Back"))
        self.forward_tbutton.setToolTip(_translate("MainWindow", "Forward"))
        self.home_tbutton.setToolTip(_translate("MainWindow", "Home"))
        self.reload_tbutton.setToolTip(_translate("MainWindow", "Reload"))
        self.url_label.setText(_translate("MainWindow", "🔒 music.youtube.com"))
        self.download_ddtbutton.setToolTip(_translate("MainWindow", "Download"))
        self.watch_in_pip_tbutton.setToolTip(_translate("MainWindow", "Watch in PiP"))
        self.settings_ddtbutton.setToolTip(_translate("MainWindow", "Settings..."))
        self.plugins_ddtbutton.setToolTip(_translate("MainWindow", "Plugins"))
        self.more_ddtbutton.setToolTip(_translate("MainWindow", "More"))
from qfluentwidgets import BodyLabel, TransparentDropDownToolButton, TransparentToolButton, TransparentToolButtonWithMenu
