# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/ui/mini_player_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniPlayerDialog(object):
    def setupUi(self, MiniPlayerDialog):
        MiniPlayerDialog.setObjectName("MiniPlayerDialog")
        MiniPlayerDialog.resize(360, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MiniPlayerDialog.sizePolicy().hasHeightForWidth())
        MiniPlayerDialog.setSizePolicy(sizePolicy)
        MiniPlayerDialog.setMinimumSize(QtCore.QSize(360, 150))
        MiniPlayerDialog.setMaximumSize(QtCore.QSize(360, 150))
        MiniPlayerDialog.setMouseTracking(True)
        MiniPlayerDialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(MiniPlayerDialog)
        self.verticalLayout.setContentsMargins(0, 18, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(16, -1, 16, 6)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.title_label = StrongBodyLabel(MiniPlayerDialog)
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.verticalLayout_2.addWidget(self.title_label)
        self.author_label = BodyLabel(MiniPlayerDialog)
        self.author_label.setStyleSheet("QLabel {\n"
"    color: lightgray;\n"
"    font-size: 13px;\n"
"}")
        self.author_label.setText("")
        self.author_label.setObjectName("author_label")
        self.verticalLayout_2.addWidget(self.author_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.thumbnail_label = QtWidgets.QLabel(MiniPlayerDialog)
        self.thumbnail_label.setMinimumSize(QtCore.QSize(60, 60))
        self.thumbnail_label.setMaximumSize(QtCore.QSize(60, 60))
        self.thumbnail_label.setText("")
        self.thumbnail_label.setScaledContents(False)
        self.thumbnail_label.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnail_label.setObjectName("thumbnail_label")
        self.horizontalLayout_2.addWidget(self.thumbnail_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(16, 3, 16, 18)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BodyLabel = BodyLabel(MiniPlayerDialog)
        self.BodyLabel.setStyleSheet("FluentLabelBase {\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:lightgray}")
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_3.addWidget(self.BodyLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.dislike_button = TransparentToolButton(MiniPlayerDialog)
        self.dislike_button.setMinimumSize(QtCore.QSize(40, 40))
        self.dislike_button.setMaximumSize(QtCore.QSize(40, 40))
        self.dislike_button.setIconSize(QtCore.QSize(20, 20))
        self.dislike_button.setObjectName("dislike_button")
        self.horizontalLayout_3.addWidget(self.dislike_button)
        self.previous_button = TransparentToolButton(MiniPlayerDialog)
        self.previous_button.setMinimumSize(QtCore.QSize(40, 40))
        self.previous_button.setMaximumSize(QtCore.QSize(40, 40))
        self.previous_button.setIconSize(QtCore.QSize(20, 20))
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_3.addWidget(self.previous_button)
        self.play_pause_button = TransparentToolButton(MiniPlayerDialog)
        self.play_pause_button.setMinimumSize(QtCore.QSize(40, 40))
        self.play_pause_button.setMaximumSize(QtCore.QSize(40, 40))
        self.play_pause_button.setIconSize(QtCore.QSize(22, 22))
        self.play_pause_button.setObjectName("play_pause_button")
        self.horizontalLayout_3.addWidget(self.play_pause_button)
        self.next_button = TransparentToolButton(MiniPlayerDialog)
        self.next_button.setMinimumSize(QtCore.QSize(40, 40))
        self.next_button.setMaximumSize(QtCore.QSize(40, 40))
        self.next_button.setIconSize(QtCore.QSize(20, 20))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_3.addWidget(self.next_button)
        self.like_button = TransparentToolButton(MiniPlayerDialog)
        self.like_button.setMinimumSize(QtCore.QSize(40, 40))
        self.like_button.setMaximumSize(QtCore.QSize(40, 40))
        self.like_button.setIconSize(QtCore.QSize(20, 20))
        self.like_button.setObjectName("like_button")
        self.horizontalLayout_3.addWidget(self.like_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.BodyLabel_2 = BodyLabel(MiniPlayerDialog)
        self.BodyLabel_2.setStyleSheet("FluentLabelBase {\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:lightgray}")
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_3.addWidget(self.BodyLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(MiniPlayerDialog)
        QtCore.QMetaObject.connectSlotsByName(MiniPlayerDialog)

    def retranslateUi(self, MiniPlayerDialog):
        _translate = QtCore.QCoreApplication.translate
        MiniPlayerDialog.setWindowTitle(_translate("MiniPlayerDialog", "Dialog"))
        self.BodyLabel.setText(_translate("MiniPlayerDialog", "NaN:NaN"))
        self.dislike_button.setToolTip(_translate("MiniPlayerDialog", "Dislike"))
        self.previous_button.setToolTip(_translate("MiniPlayerDialog", "Previous"))
        self.previous_button.setShortcut(_translate("MiniPlayerDialog", "Left"))
        self.play_pause_button.setToolTip(_translate("MiniPlayerDialog", "Play/Pause"))
        self.play_pause_button.setShortcut(_translate("MiniPlayerDialog", "Space"))
        self.next_button.setToolTip(_translate("MiniPlayerDialog", "Next"))
        self.next_button.setShortcut(_translate("MiniPlayerDialog", "Right"))
        self.like_button.setToolTip(_translate("MiniPlayerDialog", "Like"))
        self.BodyLabel_2.setText(_translate("MiniPlayerDialog", "NaN:NaN"))
from qfluentwidgets import BodyLabel, StrongBodyLabel, TransparentToolButton
