# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/ui/picture_in_picture_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PictureInPictureDialog(object):
    def setupUi(self, PictureInPictureDialog):
        PictureInPictureDialog.setObjectName("PictureInPictureDialog")
        PictureInPictureDialog.resize(360, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PictureInPictureDialog.sizePolicy().hasHeightForWidth())
        PictureInPictureDialog.setSizePolicy(sizePolicy)
        PictureInPictureDialog.setMinimumSize(QtCore.QSize(360, 150))
        PictureInPictureDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        PictureInPictureDialog.setMouseTracking(True)
        PictureInPictureDialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(PictureInPictureDialog)
        self.verticalLayout.setContentsMargins(0, 18, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(16, -1, 16, 6)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.title_label = StrongBodyLabel(PictureInPictureDialog)
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.verticalLayout_2.addWidget(self.title_label)
        self.artist_label = BodyLabel(PictureInPictureDialog)
        self.artist_label.setStyleSheet("QLabel {\n"
"    color: lightgray;\n"
"    font-size: 13px;\n"
"}")
        self.artist_label.setText("")
        self.artist_label.setObjectName("artist_label")
        self.verticalLayout_2.addWidget(self.artist_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.artwork_label = QtWidgets.QLabel(PictureInPictureDialog)
        self.artwork_label.setMinimumSize(QtCore.QSize(60, 60))
        self.artwork_label.setMaximumSize(QtCore.QSize(60, 60))
        self.artwork_label.setText("")
        self.artwork_label.setScaledContents(False)
        self.artwork_label.setAlignment(QtCore.Qt.AlignCenter)
        self.artwork_label.setObjectName("artwork_label")
        self.horizontalLayout_2.addWidget(self.artwork_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(16, 3, 16, 18)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BodyLabel = BodyLabel(PictureInPictureDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel.sizePolicy().hasHeightForWidth())
        self.BodyLabel.setSizePolicy(sizePolicy)
        self.BodyLabel.setMinimumSize(QtCore.QSize(32, 0))
        self.BodyLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BodyLabel.setStyleSheet("FluentLabelBase {\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:lightgray}")
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_3.addWidget(self.BodyLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.dislike_button = TransparentToolButton(PictureInPictureDialog)
        self.dislike_button.setMinimumSize(QtCore.QSize(40, 40))
        self.dislike_button.setMaximumSize(QtCore.QSize(40, 40))
        self.dislike_button.setIconSize(QtCore.QSize(20, 20))
        self.dislike_button.setObjectName("dislike_button")
        self.horizontalLayout_3.addWidget(self.dislike_button)
        self.previous_button = TransparentToolButton(PictureInPictureDialog)
        self.previous_button.setMinimumSize(QtCore.QSize(40, 40))
        self.previous_button.setMaximumSize(QtCore.QSize(40, 40))
        self.previous_button.setIconSize(QtCore.QSize(20, 20))
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_3.addWidget(self.previous_button)
        self.play_pause_button = TransparentToolButton(PictureInPictureDialog)
        self.play_pause_button.setMinimumSize(QtCore.QSize(40, 40))
        self.play_pause_button.setMaximumSize(QtCore.QSize(40, 40))
        self.play_pause_button.setIconSize(QtCore.QSize(22, 22))
        self.play_pause_button.setObjectName("play_pause_button")
        self.horizontalLayout_3.addWidget(self.play_pause_button)
        self.next_button = TransparentToolButton(PictureInPictureDialog)
        self.next_button.setMinimumSize(QtCore.QSize(40, 40))
        self.next_button.setMaximumSize(QtCore.QSize(40, 40))
        self.next_button.setIconSize(QtCore.QSize(20, 20))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_3.addWidget(self.next_button)
        self.like_button = TransparentToolButton(PictureInPictureDialog)
        self.like_button.setMinimumSize(QtCore.QSize(40, 40))
        self.like_button.setMaximumSize(QtCore.QSize(40, 40))
        self.like_button.setIconSize(QtCore.QSize(20, 20))
        self.like_button.setObjectName("like_button")
        self.horizontalLayout_3.addWidget(self.like_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.BodyLabel_2 = BodyLabel(PictureInPictureDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_2.sizePolicy().hasHeightForWidth())
        self.BodyLabel_2.setSizePolicy(sizePolicy)
        self.BodyLabel_2.setMinimumSize(QtCore.QSize(32, 0))
        self.BodyLabel_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BodyLabel_2.setStyleSheet("FluentLabelBase {\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:lightgray}")
        self.BodyLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_3.addWidget(self.BodyLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(PictureInPictureDialog)
        QtCore.QMetaObject.connectSlotsByName(PictureInPictureDialog)

    def retranslateUi(self, PictureInPictureDialog):
        _translate = QtCore.QCoreApplication.translate
        PictureInPictureDialog.setWindowTitle(_translate("PictureInPictureDialog", "Dialog"))
        self.BodyLabel.setText(_translate("PictureInPictureDialog", "0:38"))
        self.dislike_button.setToolTip(_translate("PictureInPictureDialog", "Dislike"))
        self.previous_button.setToolTip(_translate("PictureInPictureDialog", "Previous"))
        self.previous_button.setShortcut(_translate("PictureInPictureDialog", "Left"))
        self.play_pause_button.setToolTip(_translate("PictureInPictureDialog", "Play/Pause"))
        self.play_pause_button.setShortcut(_translate("PictureInPictureDialog", "Space"))
        self.next_button.setToolTip(_translate("PictureInPictureDialog", "Next"))
        self.next_button.setShortcut(_translate("PictureInPictureDialog", "Right"))
        self.like_button.setToolTip(_translate("PictureInPictureDialog", "Like"))
        self.BodyLabel_2.setText(_translate("PictureInPictureDialog", "2:34"))
from qfluentwidgets import BodyLabel, StrongBodyLabel, TransparentToolButton
